SavingsTarget/Models/WishlistItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SavingsTarget.Models
{
    public class WishlistItem
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public decimal Value { get; set; }

        public DateTime Date { get; set; }

        public string Description { get; set; }

      
    }
}

SavingsTarget/Controllers/UserSavingsAccountsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Net.Configuration;
using System.Web;
using System.Web.Mvc;
using SavingsTarget.Models;

namespace SavingsTarget.Controllers
{
    public class UserSavingsAccountsController : Controller
    {
        private ApplicationDbContext _context = new ApplicationDbContext();
        private string _userId;

        public UserSavingsAccountsController()
        {
            _context = new ApplicationDbContext();
        }


        protected override void OnAuthorization(AuthorizationContext filterContext)
        {
            _userId = User.Identity.GetUserId();
        }
        // GET: SavingsAccounts
        public ActionResult Index()
        {
            if (_userId == null)
                return RedirectToAction("Login", "Account");
            var savings = _context.UserSavingsAccounts.ToList().FindAll(sav => sav.UserId == _userId);

            return View(savings);
        }

        
        // GET: SavingsAccounts/Create
        public ActionResult Deposit()
        {
            if (_userId == null)
                return RedirectToAction("Login", "Account");

            return View();
        }

        // POST: SavingsAccounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Deposit([Bind(Include = "UserId,Balance,Date,Deposit")] UserSavingsAccount userSavingsAccount)
        {
            if (_userId == null)
                return RedirectToAction("Login", "Account");

            if (!ModelState.IsValid)
            
                return View(userSavingsAccount);
            userSavingsAccount.UserId = _userId;
            userSavingsAccount.Date=DateTime.Now;
            userSavingsAccount.Balance = userSavingsAccount.Deposit+_context.UserSavingsAccounts.ToList().FindAll(sav => sav.UserId == _userId).Sum(item => item.Deposit);
            _context.UserSavingsAccounts.Add(userSavingsAccount);
            _context.SaveChanges();
            return RedirectToAction("Index");
         
            
        }

        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SavingsTarget/Controllers/WishlistItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SavingsTarget.Models;
using System.Data.Entity;
using System.Net;

namespace SavingsTarget.Controllers
{
    public class WishlistItemsController : Controller
    {
        private ApplicationDbContext _context;
        private string _userId;

        public WishlistItemsController()
        {
            _context = new ApplicationDbContext();
        }
        

        protected override void OnAuthorization(AuthorizationContext filterContext)
        {
            _userId = User.Identity.GetUserId();
           
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Items
        public ActionResult Index()
        {


            if (_userId == null)
                return RedirectToAction("Login", "Account");
            var items = _context.WishlistItems.ToList().FindAll(it => it.UserId == _userId);
            var balance= _context.UserSavingsAccounts.ToList().FindAll(sav => sav.UserId == _userId).Sum(item => item.Deposit);
            ViewBag.Balance = balance;
            ViewBag.TotalExpenses= _context.WishlistItems.ToList().FindAll(exp => exp.UserId == _userId).Sum(exp => exp.Value);
            
            
            return View(items);
        }
       
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,Title,Value,Date,Description")] WishlistItem wishlistItem)
        {
            if (ModelState.IsValid)
            {
                wishlistItem.UserId = _userId;
                wishlistItem.Date = DateTime.Today;
                _context.WishlistItems.Add(wishlistItem);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(wishlistItem);
        }

        // GET: Savings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (_userId == null)
                return RedirectToAction("Login", "Account");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WishlistItem saving = _context.WishlistItems.Find(id);
            if (saving == null)
            {
                return HttpNotFound();
            }
            return View(saving);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,Title,Value,Date,Description")] WishlistItem wishlistItem)
        {
            if (ModelState.IsValid)
            {
                wishlistItem.Date=DateTime.Today;
                
                _context.Entry(wishlistItem).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(wishlistItem);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WishlistItem wishlistItem = _context.WishlistItems.Find(id);
            if (wishlistItem == null)
            {
                return HttpNotFound();
            }
            return View(wishlistItem);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WishlistItem saving = _context.WishlistItems.Find(id);
            _context.WishlistItems.Remove(saving);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


       

    }
}

SavingsTarget/Views/WishlistItems/Create.cshtml
@model SavingsTarget.Models.WishlistItem

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WishlistItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SavingsTarget/Views/WishlistItems/Delete.cshtml
@model SavingsTarget.Models.WishlistItem

@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
    
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

         <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SavingsTarget/Views/WishlistItems/Edit.cshtml
@model SavingsTarget.Models.WishlistItem

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WishlistItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserId)
       
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SavingsTarget/Views/WishlistItems/Index.cshtml
@model IEnumerable<SavingsTarget.Models.WishlistItem>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h4>@Html.ActionLink("Add  To Wishlist", "Create")</h4>



<table id="Items"class="table">
    <thead>
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.ValueFor(modelItem => item.Date, "{0:dd/MM/yyyy}")
                </td>
                <th>
                    @Html.DisplayFor(modelItem => item.Value)
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>

</table>

    <br/><br/>
<h4 align="center">Your Account Balance is<b> $@ViewBag.Balance</b></h4>
    <br />
    <h4 align="center">
        <progress class="progress progress-success" value=@ViewBag.Balance max=@ViewBag.TotalExpenses></progress>
    </h4>
   <br />
    <h4 align="center">
        You need to deposit <b>$@(ViewBag.TotalExpenses - ViewBag.Balance)</b> more to achieve your target!!!
        <br /><br />
        Click @Html.ActionLink("Here", "Deposit", "UserSavingsAccounts") to Deposit.
    </h4>
@section scripts
{
    <script>
        $(document)
            .ready(function() {
                $("#Items").DataTable();
            })
    </script>}